server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          route-id-prefix: ${spring.application.name}
      routes:
        # IAM
        - id: iam-service
          uri: lb://iam-service
          predicates:
            - Path=/api/v1/authentication/**
          #filters:
            # si tu IAM NO usa context-path, no necesitas strip. Lo dejo como ejemplo.
            #- StripPrefix=0

        # VEHICLE
        - id: vehicle-service
          uri: lb://vehicle-service
          predicates:
            - Path=/api/v1/vehicles/**
          #filters:
            #- StripPrefix=1   # quita solo /api/v1 → el backend recibe /vehicles/**

        # VEHICLE-SALES
        - id: sales
          uri: lb://sales
          predicates:
            - Path=/api/v1/sales/**
            #filters:
            #- StripPrefix=1   # quita solo /api/v1 → el backend recibe /vehicles/**

        # Perfiles
        - id: Perfilles
          uri: lb://users
          predicates:
            - Path=/api/v1/users/**
            #filters:
            #- StripPrefix=1   # quita solo /api/v1 → el backend recibe /vehicles/**

      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
            allowedHeaders: "*"
            maxAge: 3600

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}:${random.value}
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway
  endpoint:
    health:
      show-details: always
info:
  app:
    name: ${spring.application.name}
    version: ${project.version}


springdoc:
  swagger-ui:
    urls:
      - name: IAM Service
        url: /api/v1/authentication/docs
      - name: Vehicle Service
        url: /api/v1/vehicles/v3/api-docs
      - name: Vehicle Sales Service
        url: /api/v1/sales/v3/api-docs
  api-docs:
    enabled: true

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    com.netflix.discovery: INFO

